/** AUTOGENERATED - DO NOT EDIT **/
/* tslint:disable */
/* eslint-disable */

import { t_Error, t_NewPet, t_Pet } from "./models"
import qs from "querystring"

export interface ApiClientConfig {
  basePath: string
  defaultHeaders: Record<string, string>
}

export interface Res<StatusCode, Body> {
  status: StatusCode
  body: Body
}

export class ApiClient {
  constructor(private readonly config: ApiClientConfig) {}

  private _query(
    params: Record<
      string,
      string | number | boolean | string[] | undefined | null
    >
  ): string {
    const filtered = Object.fromEntries(
      Object.entries(params).filter(([k, v]) => v !== undefined)
    )

    return qs.stringify(filtered)
  }

  private _headers(
    headers: Record<string, string | undefined>
  ): Record<string, string> {
    return Object.fromEntries(
      Object.entries({ ...this.config.defaultHeaders, ...headers }).filter(
        (it): it is [string, string] => it[1] !== undefined
      )
    )
  }

  async findPets(p: {
    tags?: string[]
    limit?: number
  }): Promise<Res<200, t_Pet[]> | Res<number, t_Error>> {
    const headers: Record<string, string | undefined> = {}

    const res = await fetch(
      this.config.basePath +
        `/pets?${this._query({ tags: p["tags"], limit: p["limit"] })}`,
      {
        method: "GET",
        headers: this._headers(headers),
      }
    )

    // TODO: this is a poor assumption
    return { status: res.status as any, body: (await res.json()) as any }
  }

  async addPet(p: {
    requestBody: t_NewPet
  }): Promise<Res<200, t_Pet> | Res<number, t_Error>> {
    const headers: Record<string, string | undefined> = {
      "Content-Type": "application/json",
    }

    const res = await fetch(this.config.basePath + `/pets`, {
      method: "POST",
      headers: this._headers(headers),
      body: JSON.stringify(p.requestBody),
    })

    // TODO: this is a poor assumption
    return { status: res.status as any, body: (await res.json()) as any }
  }

  async findPetById(p: {
    id: number
  }): Promise<Res<200, t_Pet> | Res<number, t_Error>> {
    const headers: Record<string, string | undefined> = {}

    const res = await fetch(this.config.basePath + `/pets/${p["id"]}`, {
      method: "GET",
      headers: this._headers(headers),
    })

    // TODO: this is a poor assumption
    return { status: res.status as any, body: (await res.json()) as any }
  }

  async deletePet(p: {
    id: number
  }): Promise<Res<204, void> | Res<number, t_Error>> {
    const headers: Record<string, string | undefined> = {}

    const res = await fetch(this.config.basePath + `/pets/${p["id"]}`, {
      method: "DELETE",
      headers: this._headers(headers),
    })

    // TODO: this is a poor assumption
    return { status: res.status as any, body: (await res.json()) as any }
  }
}
