/** AUTOGENERATED - DO NOT EDIT **/
/* tslint:disable */
/* eslint:disable */

export type Error = {
  code: number
  message: string
}

export type NewPet = {
  name: string
  tag?: string
}

export type Pet = NewPet & {
  id: number
}
