/** AUTOGENERATED - DO NOT EDIT **/
/* tslint:disable */
/* eslint-disable */

import {
  t_DeleteTodoListByIdParamSchema,
  t_Error,
  t_GetTodoListByIdParamSchema,
  t_TodoList,
  t_UpdateTodoListByIdBodySchema,
  t_UpdateTodoListByIdParamSchema,
} from "../../../../lib/models"
import { s_CreateUpdateTodoList } from "../../../../lib/schemas"
import {
  KoaRuntimeError,
  RequestInputType,
} from "@nahkies/typescript-koa-runtime/errors"
import {
  KoaRuntimeResponder,
  KoaRuntimeResponse,
  StatusCode,
  StatusCode4xx,
} from "@nahkies/typescript-koa-runtime/server"
import { Params, parseRequestInput } from "@nahkies/typescript-koa-runtime/zod"
import { NextRequest } from "next/server"
import { z } from "zod"

//region safe-edit-region-header

//endregion safe-edit-region-header
export type GetTodoListByIdResponder = {
  with200(): KoaRuntimeResponse<t_TodoList>
  withStatusCode4xx(status: StatusCode4xx): KoaRuntimeResponse<t_Error>
  withDefault(status: StatusCode): KoaRuntimeResponse<void>
} & KoaRuntimeResponder

export type GetTodoListById = (
  params: Params<t_GetTodoListByIdParamSchema, void, void>,
  respond: GetTodoListByIdResponder,
  ctx: { request: NextRequest },
) => Promise<KoaRuntimeResponse<unknown>>

export type UpdateTodoListByIdResponder = {
  with200(): KoaRuntimeResponse<t_TodoList>
  withStatusCode4xx(status: StatusCode4xx): KoaRuntimeResponse<t_Error>
  withDefault(status: StatusCode): KoaRuntimeResponse<void>
} & KoaRuntimeResponder

export type UpdateTodoListById = (
  params: Params<
    t_UpdateTodoListByIdParamSchema,
    void,
    t_UpdateTodoListByIdBodySchema
  >,
  respond: UpdateTodoListByIdResponder,
  ctx: { request: NextRequest },
) => Promise<KoaRuntimeResponse<unknown>>

export type DeleteTodoListByIdResponder = {
  with204(): KoaRuntimeResponse<void>
  withStatusCode4xx(status: StatusCode4xx): KoaRuntimeResponse<t_Error>
  withDefault(status: StatusCode): KoaRuntimeResponse<void>
} & KoaRuntimeResponder

export type DeleteTodoListById = (
  params: Params<t_DeleteTodoListByIdParamSchema, void, void>,
  respond: DeleteTodoListByIdResponder,
  ctx: { request: NextRequest },
) => Promise<KoaRuntimeResponse<unknown>>

const getTodoListByIdParamSchema = z.object({ listId: z.string() })

export const GET = async (
  request: NextRequest,
  { params }: { params: unknown },
): Promise<Response> => {
  const input = {
    params: parseRequestInput(
      getTodoListByIdParamSchema,
      params,
      RequestInputType.RouteParam,
    ),
    // TODO: this swallows repeated parameters
    query: undefined,
    body: undefined,
  }

  const responder = {
    with200() {
      return new KoaRuntimeResponse<t_TodoList>(200)
    },
    withStatusCode4xx(status: StatusCode4xx) {
      return new KoaRuntimeResponse<t_Error>(status)
    },
    withDefault(status: StatusCode) {
      return new KoaRuntimeResponse<void>(status)
    },
    withStatus(status: StatusCode) {
      return new KoaRuntimeResponse(status)
    },
  }

  const { status, body } = await import("@/lib/api/list/[listId]/route")
    .then((it) => it.GET(input, responder, { request }))
    .then((it) => it.unpack())
    .catch((err) => {
      throw KoaRuntimeError.HandlerError(err)
    })

  return Response.json(body, { status })
}

const updateTodoListByIdParamSchema = z.object({ listId: z.string() })

const updateTodoListByIdBodySchema = s_CreateUpdateTodoList

export const PUT = async (
  request: NextRequest,
  { params }: { params: unknown },
): Promise<Response> => {
  const input = {
    params: parseRequestInput(
      updateTodoListByIdParamSchema,
      params,
      RequestInputType.RouteParam,
    ),
    // TODO: this swallows repeated parameters
    query: undefined,
    body: parseRequestInput(
      updateTodoListByIdBodySchema,
      await request.json(),
      RequestInputType.RequestBody,
    ),
  }

  const responder = {
    with200() {
      return new KoaRuntimeResponse<t_TodoList>(200)
    },
    withStatusCode4xx(status: StatusCode4xx) {
      return new KoaRuntimeResponse<t_Error>(status)
    },
    withDefault(status: StatusCode) {
      return new KoaRuntimeResponse<void>(status)
    },
    withStatus(status: StatusCode) {
      return new KoaRuntimeResponse(status)
    },
  }

  const { status, body } = await import("@/lib/api/list/[listId]/route")
    .then((it) => it.GET(input, responder, { request }))
    .then((it) => it.unpack())
    .catch((err) => {
      throw KoaRuntimeError.HandlerError(err)
    })

  return Response.json(body, { status })
}

const deleteTodoListByIdParamSchema = z.object({ listId: z.string() })

export const DELETE = async (
  request: NextRequest,
  { params }: { params: unknown },
): Promise<Response> => {
  const input = {
    params: parseRequestInput(
      deleteTodoListByIdParamSchema,
      params,
      RequestInputType.RouteParam,
    ),
    // TODO: this swallows repeated parameters
    query: undefined,
    body: undefined,
  }

  const responder = {
    with204() {
      return new KoaRuntimeResponse<void>(204)
    },
    withStatusCode4xx(status: StatusCode4xx) {
      return new KoaRuntimeResponse<t_Error>(status)
    },
    withDefault(status: StatusCode) {
      return new KoaRuntimeResponse<void>(status)
    },
    withStatus(status: StatusCode) {
      return new KoaRuntimeResponse(status)
    },
  }

  const { status, body } = await import("@/lib/api/list/[listId]/route")
    .then((it) => it.GET(input, responder, { request }))
    .then((it) => it.unpack())
    .catch((err) => {
      throw KoaRuntimeError.HandlerError(err)
    })

  return Response.json(body, { status })
}
