packages:
  - packages/*
  - integration-tests/*
  - e2e

minimumReleaseAge: 10080 # 7 days in minutes

minimumReleaseAgeExclude:
  # Renovate security update: lodash@4.17.23
  - lodash@4.17.23
  - '@isaacs/brace-expansion@5.0.1'
  # Renovate security update: axios@1.13.5
  - axios@1.13.5

nodeOptions: "${NODE_OPTIONS:- } --experimental-vm-modules"

dedupeInjectedDeps: true

linkWorkspacePackages: deep

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - sharp
  - unrs-resolver

overrides:
  '@types/node': 22.16.5
  'zod@4.1.11': '4.1.13'
  '@isaacs/brace-expansion': 5.0.1
  tar: 7.5.7

preferWorkspacePackages: true

publicHoistPattern:
  - '@typespec/*'
  - '@azure-tools/*'
  - '@types/node'
  - '@biomejs/biome'

# GH actions doesn't checkout the branch
gitChecks: false
