packages:
  - packages/*
  - integration-tests/*
  - e2e

minimumReleaseAge: 10080 # 7 days in minutes

minimumReleaseAgeExclude:
  - 'next@16.1.0'
  - '@next/env@16.1.0'
  - '@next/swc-darwin-arm64@16.1.0'
  - '@next/swc-darwin-x64@16.1.0'
  - '@next/swc-linux-arm64-gnu@16.1.0'
  - '@next/swc-linux-arm64-musl@16.1.0'
  - '@next/swc-linux-x64-gnu@16.1.0'
  - '@next/swc-linux-x64-musl@16.1.0'
  - '@next/swc-win32-arm64-msvc@16.1.0'
  - '@next/swc-win32-x64-msvc@16.1.0'

nodeOptions: "${NODE_OPTIONS:- } --experimental-vm-modules"

dedupeInjectedDeps: true

linkWorkspacePackages: deep

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - sharp
  - unrs-resolver

overrides:
  '@types/node': 22.16.5
  'zod@4.1.11': '4.1.13'

preferWorkspacePackages: true

publicHoistPattern:
  - '@typespec/*'
  - '@azure-tools/*'
  - '@types/node'
  - '@biomejs/biome'

# GH actions doesn't checkout the branch
gitChecks: false
