packages:
  - packages/*
  - integration-tests/*
  - e2e

dedupeInjectedDeps: true

gitChecks: false

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - sharp
  - unrs-resolver

linkWorkspacePackages: deep

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - lodash@4.17.23
  - '@isaacs/brace-expansion@5.0.1'
  - axios@1.13.5

nodeOptions: ${NODE_OPTIONS:- } --experimental-vm-modules

overrides:
  '@isaacs/brace-expansion': 5.0.1
  '@types/node': 22.16.5
  tar: 7.5.7
  zod@4.1.11: 4.1.13

patchedDependencies:
  axios: patches/axios.patch

preferWorkspacePackages: true

publicHoistPattern:
  - '@typespec/*'
  - '@azure-tools/*'
  - '@types/node'
  - '@biomejs/biome'
