packages:
  - packages/*
  - integration-tests/*
  - e2e

minimumReleaseAge: 10080 # 7 days in minutes

minimumReleaseAgeExclude:
  - 'next@15.5.7'
  - '@next/env@15.5.7'
  - '@next/swc-darwin-arm64@15.5.7'
  - '@next/swc-darwin-x64@15.5.7'
  - '@next/swc-linux-arm64-gnu@15.5.7'
  - '@next/swc-linux-arm64-musl@15.5.7'
  - '@next/swc-linux-x64-gnu@15.5.7'
  - '@next/swc-linux-x64-musl@15.5.7'
  - '@next/swc-win32-arm64-msvc@15.5.7'
  - '@next/swc-win32-x64-msvc@15.5.7'

dedupeInjectedDeps: true

linkWorkspacePackages: deep

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - lmdb
  - nx
  - sharp
  - unrs-resolver

overrides:
  '@types/node': 22.16.5

preferWorkspacePackages: true

publicHoistPattern:
  - '@typespec/*'
  - '@azure-tools/*'
  - '@types/node'

# GH actions doesn't checkout the branch
gitChecks: false
