packages:
  - packages/*
  - integration-tests/*
  - e2e

minimumReleaseAge: 10080 # 7 days in minutes

dedupeInjectedDeps: true

linkWorkspacePackages: deep

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - sharp
  - unrs-resolver

overrides:
  '@types/node': 22.16.5

preferWorkspacePackages: true

publicHoistPattern:
  - '@typespec/*'
  - '@azure-tools/*'
  - '@types/node'

# GH actions doesn't checkout the branch
gitChecks: false
