packages:
  - packages/*
  - integration-tests/*
  - e2e

minimumReleaseAge: 10080 # 7 days in minutes

minimumReleaseAgeExclude:
  # Renovate security update: next@16.1.5
  - 'next@16.1.0 || 16.1.5'
  - '@next/env@16.1.0'
  - '@next/swc-darwin-arm64@16.1.0'
  - '@next/swc-darwin-x64@16.1.0'
  - '@next/swc-linux-arm64-gnu@16.1.0'
  - '@next/swc-linux-arm64-musl@16.1.0'
  - '@next/swc-linux-x64-gnu@16.1.0'
  - '@next/swc-linux-x64-musl@16.1.0'
  - '@next/swc-win32-arm64-msvc@16.1.0'
  - '@next/swc-win32-x64-msvc@16.1.0'
  - "@biomejs/biome@2.3.10"
  - "@biomejs/wasm-nodejs@2.3.10"
  - "@biomejs/cli-linux-x64-musl@2.3.10"
  - "@biomejs/cli-linux-arm64-musl@2.3.10"
  - "@biomejs/cli-linux-arm64@2.3.10"
  - "@biomejs/cli-darwin-arm64@2.3.10"
  - "@biomejs/cli-linux-x64@2.3.10"
  - "@biomejs/cli-win32-x64@2.3.10"
  - "@biomejs/cli-darwin-x64@2.3.10"
  - "@biomejs/cli-win32-arm64@2.3.10"
  # Renovate security update: lodash@4.17.23
  - lodash@4.17.23

nodeOptions: "${NODE_OPTIONS:- } --experimental-vm-modules"

dedupeInjectedDeps: true

linkWorkspacePackages: deep

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - sharp
  - unrs-resolver

overrides:
  '@types/node': 22.16.5
  'zod@4.1.11': '4.1.13'

preferWorkspacePackages: true

publicHoistPattern:
  - '@typespec/*'
  - '@azure-tools/*'
  - '@types/node'
  - '@biomejs/biome'

# GH actions doesn't checkout the branch
gitChecks: false
