import {describe, expect, it} from "vitest"
import {testFsAdaptor} from "../../../core/file-system/test-fs-adaptor.ts"
import type {Input} from "../../../core/input.ts"
import {FakeSchemaProvider} from "../../../test/fake-schema-provider.ts"
import {irFixture as ir} from "../../../test/ir-model.fixtures.test-utils.ts"
import {TypescriptEmitter} from "../../common/typescript-emitter.ts"
import {TypescriptFormatterBiome} from "../../common/typescript-formatter.biome.ts"
import {generateTypescriptPlainSchema} from "./typescript-plain.generator.ts"

describe("generateTypescriptJsonSchema", () => {
  it("should not import from itself", async () => {
    const input = new FakeSchemaProvider()
    const formatter = await TypescriptFormatterBiome.createNodeFormatter()
    const fs = testFsAdaptor({})
    const emitter = new TypescriptEmitter(fs, formatter, {
      allowUnusedImports: false,
      destinationDirectory: "/dist/",
    })

    const addressFilename = "address.json"
    const userFilename = "user.json"

    input.registerJsonSchemaDocument(
      addressFilename,
      ir.object({
        properties: {
          street: ir.string(),
        },
      }),
    )

    input.registerJsonSchemaDocument(
      userFilename,
      ir.object({
        properties: {
          name: ir.string(),
          address: {$ref: addressFilename},
          self: {$ref: userFilename},
        },
      }),
    )

    await generateTypescriptPlainSchema({
      enableRuntimeResponseValidation: false,
      enableTypedBasePaths: false,
      filenameConvention: "snake-case",
      groupingStrategy: "none",
      serverImplementationMethod: "type",
      input: input as unknown as Input,
      emitter,
      schemaBuilder: "zod-v4",
      compilerOptions: {},
      allowAny: false,
      isEsmProject: true,
    })

    expect(fs.files.get("/dist/user.ts")).toMatchInlineSnapshot(`
      "/** AUTOGENERATED - DO NOT EDIT **/
      /* tslint:disable */
      /* eslint-disable */

      import { z } from "zod/v4"
      import { s_address, type t_address } from "./address.ts"

      export type t_user = {
        address?: t_address
        name?: string
        self?: t_user
      }

      export const s_user: z.ZodType<t_user> = z.object({
        name: z.string().optional(),
        address: s_address.optional(),
        self: z.lazy(() => s_user.optional()),
      })
      "
    `)
    expect(fs.files.get("/dist/address.ts")).toMatchInlineSnapshot(`
      "/** AUTOGENERATED - DO NOT EDIT **/
      /* tslint:disable */
      /* eslint-disable */

      import { z } from "zod/v4"

      export type t_address = {
        street?: string
      }

      export const s_address = z.object({ street: z.string().optional() })
      "
    `)
  })
})
