/** AUTOGENERATED - DO NOT EDIT **/
/* tslint:disable */
/* eslint-disable */

import {
  ServerConfig,
  startServer,
} from "@nahkies/typescript-koa-runtime/server"

export async function bootstrap(config: ServerConfig) {
  // Todo Lists Example API
  return startServer(config)
}
