/** AUTOGENERATED - DO NOT EDIT **/
/* tslint:disable */
/* eslint:disable */

export type Error = {
  code?: number
  message?: string
}

export type CreateUpdateTodoList = {
  name: string
}

export type TodoList = {
  created: string
  id: string
  incompleteItemCount: number
  name: string
  totalItemCount: number
  updated: string
}
