/** AUTOGENERATED - DO NOT EDIT **/
/* tslint:disable */
/* eslint:disable */

export type DeleteTodoListByIdParamSchema = {
  listId?: string
}

export type GetTodoListByIdParamSchema = {
  listId?: string
}

export type UpdateTodoListByIdBodySchema = {
  name: string
}

export type UpdateTodoListByIdParamSchema = {
  listId?: string
}
