/** AUTOGENERATED - DO NOT EDIT **/
/* tslint:disable */
/* eslint:disable */

export type t_DeleteTodoListByIdParamSchema = {
  listId?: string
}

export type t_GetTodoListByIdParamSchema = {
  listId?: string
}

export type t_UpdateTodoListByIdBodySchema = {
  name: string
}

export type t_UpdateTodoListByIdParamSchema = {
  listId?: string
}
