/** AUTOGENERATED - DO NOT EDIT **/
/* tslint:disable */
/* eslint-disable */

import {
  t_CreateTodoListItemBodySchema,
  t_CreateTodoListItemParamSchema,
  t_GetTodoListItemsParamSchema,
} from "../../../../../lib/models"
import {
  KoaRuntimeError,
  RequestInputType,
} from "@nahkies/typescript-koa-runtime/errors"
import {
  KoaRuntimeResponder,
  KoaRuntimeResponse,
  StatusCode,
  StatusCode5xx,
} from "@nahkies/typescript-koa-runtime/server"
import { Params, parseRequestInput } from "@nahkies/typescript-koa-runtime/zod"
import { NextRequest } from "next/server"
import { z } from "zod"

//region safe-edit-region-header

//endregion safe-edit-region-header
export type GetTodoListItemsResponder = {
  with200(): KoaRuntimeResponse<{
    completedAt?: string
    content: string
    createdAt: string
    id: string
  }>
  withStatusCode5xx(status: StatusCode5xx): KoaRuntimeResponse<{
    code: string
    message: string
  }>
} & KoaRuntimeResponder

export type GetTodoListItems = (
  params: Params<t_GetTodoListItemsParamSchema, void, void>,
  respond: GetTodoListItemsResponder,
  ctx: { request: NextRequest },
) => Promise<KoaRuntimeResponse<unknown>>

export type CreateTodoListItemResponder = {
  with204(): KoaRuntimeResponse<void>
} & KoaRuntimeResponder

export type CreateTodoListItem = (
  params: Params<
    t_CreateTodoListItemParamSchema,
    void,
    t_CreateTodoListItemBodySchema
  >,
  respond: CreateTodoListItemResponder,
  ctx: { request: NextRequest },
) => Promise<KoaRuntimeResponse<unknown>>

const getTodoListItemsParamSchema = z.object({ listId: z.string() })

export const GET = async (
  request: NextRequest,
  { params }: { params: unknown },
): Promise<Response> => {
  const input = {
    params: parseRequestInput(
      getTodoListItemsParamSchema,
      params,
      RequestInputType.RouteParam,
    ),
    // TODO: this swallows repeated parameters
    query: undefined,
    body: undefined,
  }

  const responder = {
    with200() {
      return new KoaRuntimeResponse<{
        completedAt?: string
        content: string
        createdAt: string
        id: string
      }>(200)
    },
    withStatusCode5xx(status: StatusCode5xx) {
      return new KoaRuntimeResponse<{
        code: string
        message: string
      }>(status)
    },
    withStatus(status: StatusCode) {
      return new KoaRuntimeResponse(status)
    },
  }

  const { status, body } = await import("@/lib/api/list/[listId]/items/route")
    .then((it) => it.GET(input, responder, { request }))
    .then((it) => it.unpack())
    .catch((err) => {
      throw KoaRuntimeError.HandlerError(err)
    })

  return Response.json(body, { status })
}

const createTodoListItemParamSchema = z.object({ listId: z.string() })

const createTodoListItemBodySchema = z.object({
  id: z.string(),
  content: z.string(),
  completedAt: z.string().datetime({ offset: true }).optional(),
})

export const POST = async (
  request: NextRequest,
  { params }: { params: unknown },
): Promise<Response> => {
  const input = {
    params: parseRequestInput(
      createTodoListItemParamSchema,
      params,
      RequestInputType.RouteParam,
    ),
    // TODO: this swallows repeated parameters
    query: undefined,
    body: parseRequestInput(
      createTodoListItemBodySchema,
      await request.json(),
      RequestInputType.RequestBody,
    ),
  }

  const responder = {
    with204() {
      return new KoaRuntimeResponse<void>(204)
    },
    withStatus(status: StatusCode) {
      return new KoaRuntimeResponse(status)
    },
  }

  const { status, body } = await import("@/lib/api/list/[listId]/items/route")
    .then((it) => it.GET(input, responder, { request }))
    .then((it) => it.unpack())
    .catch((err) => {
      throw KoaRuntimeError.HandlerError(err)
    })

  return Response.json(body, { status })
}
