/** AUTOGENERATED - DO NOT EDIT **/
/* tslint:disable */
/* eslint-disable */

import { t_Error, t_NewPet, t_Pet } from "./models"
import { HttpClient, HttpHeaders, HttpParams } from "@angular/common/http"
import { Injectable } from "@angular/core"
import { Observable } from "rxjs"

export class ApiClientConfig {
  basePath: string = ""
  defaultHeaders: Record<string, string> = {}
}

export interface Res<StatusCode, Body> {
  status: StatusCode
  body: Body
}

export type QueryParams = {
  [name: string]:
    | string
    | number
    | boolean
    | string[]
    | undefined
    | null
    | QueryParams
    | QueryParams[]
}

@Injectable({
  providedIn: "root",
})
export class ApiClient {
  constructor(
    private readonly httpClient: HttpClient,
    private readonly config: ApiClientConfig
  ) {}

  private _headers(
    headers: Record<string, string | undefined>
  ): Record<string, string> {
    return Object.fromEntries(
      Object.entries({ ...this.config.defaultHeaders, ...headers }).filter(
        (it): it is [string, string] => it[1] !== undefined
      )
    )
  }

  private _queryParams(queryParams: QueryParams): HttpParams {
    return Object.entries(queryParams).reduce((result, [name, value]) => {
      if (
        typeof value === "string" ||
        typeof value === "boolean" ||
        typeof value === "number"
      ) {
        return result.set(name, value)
      } else if (value === null || value === undefined) {
        return result
      }
      throw new Error(
        `query parameter '${name}' with value '${value}' is not yet supported`
      )
    }, new HttpParams())
  }

  findPets(
    p: {
      tags?: string[]
      limit?: number
    } = {}
  ): Observable<t_Pet[] | t_Error> {
    const params = this._queryParams({ tags: p["tags"], limit: p["limit"] })

    return this.httpClient.request<any>("GET", this.config.basePath + `/pets`, {
      params,
      observe: "body",
      reportProgress: false,
    })
  }

  addPet(p: { requestBody: t_NewPet }): Observable<t_Pet | t_Error> {
    const headers = this._headers({ "Content-Type": "application/json" })
    const body = p["requestBody"]

    return this.httpClient.request<any>(
      "POST",
      this.config.basePath + `/pets`,
      {
        headers,
        body,
        observe: "body",
        reportProgress: false,
      }
    )
  }

  findPetById(p: { id: number }): Observable<t_Pet | t_Error> {
    return this.httpClient.request<any>(
      "GET",
      this.config.basePath + `/pets/${p["id"]}`,
      {
        observe: "body",
        reportProgress: false,
      }
    )
  }

  deletePet(p: { id: number }): Observable<void | t_Error> {
    return this.httpClient.request<any>(
      "DELETE",
      this.config.basePath + `/pets/${p["id"]}`,
      {
        observe: "body",
        reportProgress: false,
      }
    )
  }
}
