/** AUTOGENERATED - DO NOT EDIT **/
/* tslint:disable */
/* eslint:disable */

import {
  t_AddPetBodySchema,
  t_DeletePetParamSchema,
  t_FindPetByIdParamSchema,
  t_FindPetsQuerySchema,
} from "./models"
import joi from "@hapi/joi"
import cors from "@koa/cors"
import KoaRouter from "@koa/router"
import Koa, { Context, Middleware, Next } from "koa"
import koaBody from "koa-body"

//region safe-edit-region-header
//endregion safe-edit-region-header

function paramValidationFactory<Type>(
  schema: joi.Schema
): Middleware<{ params: Type }> {
  return async function (ctx: Context, next: Next) {
    const result = schema.validate(ctx.params, { stripUnknown: true })

    if (result.error) {
      throw new Error("validation error")
    }

    ctx.state.params = result.value

    return next()
  }
}

function queryValidationFactory<Type>(
  schema: joi.Schema
): Middleware<{ query: Type }> {
  return async function (ctx: Context, next: Next) {
    const result = schema.validate(ctx.query, { stripUnknown: true })

    if (result.error) {
      throw new Error("validation error")
    }

    ctx.state.query = result.value

    return next()
  }
}

function bodyValidationFactory<Type>(
  schema: joi.Schema
): Middleware<{ body: Type }> {
  return async function (ctx: Context, next: Next) {
    const result = schema.validate(ctx.request.body, { stripUnknown: true })

    if (result.error) {
      throw new Error("validation error")
    }

    ctx.state.body = result.value

    return next()
  }
}

interface ValidatedCtx<Params, Query, Body> extends Context {
  state: { params: Params; query: Query; body: Body }
}

const PORT = 3000

// ApiClient
const server = new Koa()

server.use(cors())
server.use(koaBody())

const router = new KoaRouter()

const findPetsQuerySchema = joi
  .object()
  .keys({ tags: joi.array().items(joi.string()), limit: joi.number() })
  .required()

router.get(
  "findPets",
  "/pets",
  queryValidationFactory<t_FindPetsQuerySchema>(findPetsQuerySchema),
  async (ctx: ValidatedCtx<void, t_FindPetsQuerySchema, void>, next: Next) => {
    //region safe-edit-region-findPets

    ctx.status = 501
    ctx.body = { error: "not implemented" }
    return next()

    //endregion safe-edit-region-findPets
  }
)

const addPetBodySchema = joi
  .object()
  .keys({ name: joi.string().required(), tag: joi.string() })
  .required()

router.post(
  "addPet",
  "/pets",
  bodyValidationFactory<t_AddPetBodySchema>(addPetBodySchema),
  async (ctx: ValidatedCtx<void, void, t_AddPetBodySchema>, next: Next) => {
    //region safe-edit-region-addPet

    ctx.status = 501
    ctx.body = { error: "not implemented" }
    return next()

    //endregion safe-edit-region-addPet
  }
)

const findPetByIdParamSchema = joi
  .object()
  .keys({ id: joi.number().required() })
  .required()

router.get(
  "findPetById",
  "/pets/:id",
  paramValidationFactory<t_FindPetByIdParamSchema>(findPetByIdParamSchema),
  async (
    ctx: ValidatedCtx<t_FindPetByIdParamSchema, void, void>,
    next: Next
  ) => {
    //region safe-edit-region-findPetById

    ctx.status = 200
    ctx.body = {
      name: "Jake",
      breed: "border-collie",
    }
    return next()

    //endregion safe-edit-region-findPetById
  }
)

const deletePetParamSchema = joi
  .object()
  .keys({ id: joi.number().required() })
  .required()

router.delete(
  "deletePet",
  "/pets/:id",
  paramValidationFactory<t_DeletePetParamSchema>(deletePetParamSchema),
  async (ctx: ValidatedCtx<t_DeletePetParamSchema, void, void>, next: Next) => {
    //region safe-edit-region-deletePet

    ctx.status = 501
    ctx.body = { error: "not implemented" }
    return next()

    //endregion safe-edit-region-deletePet
  }
)

server.use(router.allowedMethods())
server.use(router.routes())

server.listen(PORT, () => {
  console.info("server listening", { port: PORT })
})
