/** AUTOGENERATED - DO NOT EDIT **/
/* tslint:disable */
/* eslint:disable */

export type AddPetBodySchema = {
  name: string
  tag?: string
}

export type DeletePetParamSchema = {
  id?: number
  species?: string
}

export type FindPetByIdParamSchema = {
  id?: number
  species?: string
}

export type FindPetsQuerySchema = {
  limit?: number
  tags?: string[]
}
