/** AUTOGENERATED - DO NOT EDIT **/
/* tslint:disable */
/* eslint:disable */

export type t_AddPetBodySchema = {
  name: string
  tag?: string
}

export type t_DeletePetParamSchema = {
  id?: number
}

export type t_FindPetByIdParamSchema = {
  id?: number
}

export type t_FindPetsQuerySchema = {
  limit?: number
  tags?: string[]
}
