import fs from "fs"
import path from "path"
import {Biome, Distribution} from "@biomejs/js-api"
import {CompilationUnit} from "../../core/compilation-units"
import {logger} from "../../core/logger"

const FILE_HEADER = `/** AUTOGENERATED - DO NOT EDIT **/
/* tslint:disable */
/* eslint-disable */
`

export async function loadPreviousResult(
  dest: string,
  unit: CompilationUnit,
): Promise<string> {
  if (!fs.existsSync(path.join(dest, unit.filename))) {
    return ""
  }
  return fs.readFileSync(path.join(dest, unit.filename), {
    encoding: "utf-8",
  })
}

export async function emitGenerationResult(
  dest: string,
  units: CompilationUnit[],
): Promise<void> {
  const outputs = units
    .filter((it) => it.toString().trim().length)
    .map((unit) => {
      return {
        filename: unit.filename,
        data: [FILE_HEADER, unit.toString()].join("\n"),
      }
    })

  logger.time("format output")

  for (const output of outputs) {
    output.data = await formatOutput(output.data, output.filename)
  }

  logger.time("write output")

  for (const output of outputs) {
    await writeOutput(dest, output.filename, output.data)
  }
}

export async function formatOutput(
  raw: string,
  filename: string,
): Promise<string> {
  try {
    const biome = await Biome.create({
      distribution: Distribution.NODE,
    })

    biome.applyConfiguration({
      organizeImports: {
        enabled: true,
      },
      files: {
        maxSize: 5 * 1024 * 1024,
      },
      formatter: {
        enabled: true,
        indentWidth: 2,
        indentStyle: "space",
      },
      javascript: {
        formatter: {
          bracketSpacing: true,
          semicolons: "asNeeded",
        },
      },
    })

    const formatted = biome.formatContent(raw, {
      filePath: filename,
    })

    return formatted.content
  } catch (err) {
    logger.error("failed to format", {err})
    return raw
  }
}

async function writeOutput(
  baseDirectory: string,
  filename: string,
  data: string,
) {
  const outputDirectory = path.dirname(path.join(baseDirectory, filename))
  const outputFilepath = path.join(baseDirectory, filename)

  fs.mkdirSync(outputDirectory, {recursive: true})

  fs.writeFileSync(outputFilepath, data, {
    encoding: "utf-8",
  })

  logger.info(`Wrote ${outputFilepath}`)
}
