/** AUTOGENERATED - DO NOT EDIT **/
/* tslint:disable */
/* eslint-disable */

import { t_GetTodoListsQuerySchema, t_TodoList } from "../../../lib/models"
import {
  KoaRuntimeError,
  RequestInputType,
} from "@nahkies/typescript-koa-runtime/errors"
import {
  KoaRuntimeResponder,
  KoaRuntimeResponse,
  StatusCode,
} from "@nahkies/typescript-koa-runtime/server"
import { Params, parseRequestInput } from "@nahkies/typescript-koa-runtime/zod"
import { NextRequest } from "next/server"
import { z } from "zod"

//region safe-edit-region-header

//endregion safe-edit-region-header
export type GetTodoListsResponder = {
  with200(): KoaRuntimeResponse<t_TodoList[]>
} & KoaRuntimeResponder

export type GetTodoLists = (
  params: Params<void, t_GetTodoListsQuerySchema, void>,
  respond: GetTodoListsResponder,
  ctx: { request: NextRequest },
) => Promise<KoaRuntimeResponse<unknown>>

const getTodoListsQuerySchema = z.object({
  created: z.string().datetime({ offset: true }).optional(),
  status: z.enum(["incomplete", "complete"]).optional(),
})

export const GET = async (
  request: NextRequest,
  { params }: { params: unknown },
): Promise<Response> => {
  const input = {
    params: undefined,
    // TODO: this swallows repeated parameters
    query: parseRequestInput(
      getTodoListsQuerySchema,
      Object.fromEntries(request.nextUrl.searchParams.entries()),
      RequestInputType.QueryString,
    ),
    body: undefined,
  }

  const responder = {
    with200() {
      return new KoaRuntimeResponse<t_TodoList[]>(200)
    },
    withStatus(status: StatusCode) {
      return new KoaRuntimeResponse(status)
    },
  }

  const { status, body } = await import("@/lib/api/list/route")
    .then((it) => it.GET(input, responder, { request }))
    .then((it) => it.unpack())
    .catch((err) => {
      throw KoaRuntimeError.HandlerError(err)
    })

  return Response.json(body, { status })
}
