/** AUTOGENERATED - DO NOT EDIT **/
/* tslint:disable */
/* eslint-disable */

import { ApiClient } from "./client.service"
import { NgModule } from "@angular/core"

@NgModule({
  imports: [],
  declarations: [],
  exports: [],
  providers: [ApiClient],
})
export class ApiModule {}
