/** AUTOGENERATED - DO NOT EDIT **/
// @ts-nocheck
/* istanbul ignore file */
/* c8 ignore start */

import {logger} from "../logger.ts"

export default function validate() {
  logger.warn(
    "Skipping validation due to https://github.com/mnahkies/openapi-code-generator/issues/103",
  )
  return true
}

/* c8 ignore end */
