# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn --immutable
    - run: yarn ci-build
    - run: yarn ci-test
    - run: yarn ci-lint
    - run: yarn ci-format
    - run: yarn integration:generate
    - run: yarn integration:validate
    - name: Check for uncommitted changes
      run: |
        if [ -n "$(git status --porcelain=v1)" ]; then
          echo "Uncommitted changes to repo found!"
          exit 1
        fi
    - name: Publish to NPM
      run: echo 'publish release' #yarn lerna publish --no-private --force-publish
      if: github.ref == 'refs/heads/main'
    - name: Publish to NPM (Alpha)
      run: echo 'publish alpha release' #yarn lerna publish --no-private --force-publish --canary
      if: github.ref != 'refs/heads/main'
