name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: nextjs-cache
        with:
          path: packages/documentation/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-

      - run: pnpm install --frozen-lockfile

      - run: pnpm ci-build
      - run: pnpm ci-test
      - run: pnpm ci-lint

      - run: pnpm install --frozen-lockfile

      - run: pnpm integration:generate
      - run: pnpm integration:validate

      - run: pnpm e2e:generate
      - run: pnpm e2e:validate

      - name: Check for uncommitted changes
        run: ./scripts/assert-clean-working-directory.sh
# TODO: figure out how to do this safely, eg: no risk of external contributors exfiltrating publish secret.
#    - name: Configure Git User
#      run: |
#        git config --global user.email "support@nahkies.co.nz"
#        git config --global user.name "$GITHUB_ACTOR"
#
#    - name: Check if able to publish changes
#      run: npm whoami
#      env:
#        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#
#    - name: Publish to NPM
#      run: echo 'publish release' #pnpm lerna publish --no-private --force-publish --yes --conventional-commits
#      if: github.ref == 'refs/heads/main'
#      env:
#        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#
#    - name: Publish to NPM (Alpha)
#      run: echo 'publish alpha release' #pnpm lerna publish --no-private --force-publish --yes --conventional-commits --canary
#      if: github.ref != 'refs/heads/main'
#      env:
#        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
